[11155931]
endpoint_url = "${RPC_11155931}"

[11155931.bool]
is_testnet = true

[11155931.address]
funder_owner = "0x584b5274765a7f7c78fdc960248f38e5ad6b1edb"
funder_signer = "0x584b5274765a7f7c78fdc960248f38e5ad6b1edb"
settler_owner = "0x0000000000000000000000000000000000000000"
l0_settler_owner = "0x0000000000000000000000000000000000000000"
l0_settler_signer = "0x0000000000000000000000000000000000000000"
layerzero_endpoint = "0x0000000000000000000000000000000000000000"
layerzero_settler_address = "0x0000000000000000000000000000000000000000"
layerzero_send_uln302 = "0x0000000000000000000000000000000000000000"
layerzero_receive_uln302 = "0x0000000000000000000000000000000000000000"
dvn_layerzero_labs = "0x0000000000000000000000000000000000000000"
dvn_google_cloud = "0x0000000000000000000000000000000000000000"
exp_minter_address = "0x0000000000000000000000000000000000000000"
supported_orchestrators = ["0xcb5CEf3C54aa90e9A7ad602A258D3d360cC862B9"]
orchestrator_deployed = "0xcb5CEf3C54aa90e9A7ad602A258D3d360cC862B9"
ithaca_account_deployed = "0x33aD2F49ab9f122f5F0FDF579f575724EfF353DE"
simulator_deployed = "0xb100Dc6e1BA9e54965fBB865F65Ac42b28BC25E8"
simple_funder_deployed = "0x19E13F4cf8Efac2e6D5bec7a4052a37FfbbFc576"
escrow_deployed = "0xf841803188076c7198852a9827059c30Fe4f0CAD"
simple_settler_deployed = "0xe5e477d959A78152FB87Cd77ba8793f7f5BAdfDc"
account_proxy_deployed = "0x4F4ddE38Da9F8AbBb96C48cA520b992D4bADc3D6"

[11155931.uint]
chain_id = 11155931
layerzero_eid = 0
target_balance = "50000000000000000"
default_num_signers = 2
layerzero_confirmations = 1
layerzero_max_message_size = 10000
layerzero_optional_dvn_threshold = 0
exp_mint_amount = "1000000000000000000000"
layerzero_destination_chain_ids = []

[11155931.bytes32]
salt = "0xdf08a9fa957a9ac004f84f3a8ab7318a7be55d59948f46497bd3717865295b61"

[11155931.string]
name = "RISE Testnet"
contracts = [
    "Orchestrator",
    "IthacaAccount",
    "Simulator",
    "SimpleFunder",
    "AccountProxy",
]
layerzero_required_dvns = ["dvn_layerzero_labs"]
layerzero_optional_dvns = []

[84532]
endpoint_url = "${RPC_84532}"

[84532.bool]
is_testnet = true

[84532.address]
funder_owner = "0x584b5274765a7f7c78fdc960248f38e5ad6b1edb"
funder_signer = "0x584b5274765a7f7c78fdc960248f38e5ad6b1edb"
settler_owner = "0x0000000000000000000000000000000000000000"
l0_settler_owner = "0x0000000000000000000000000000000000000000"
l0_settler_signer = "0x0000000000000000000000000000000000000000"
layerzero_endpoint = "0x0000000000000000000000000000000000000000"
layerzero_settler_address = "0x0000000000000000000000000000000000000000"
layerzero_send_uln302 = "0x0000000000000000000000000000000000000000"
layerzero_receive_uln302 = "0x0000000000000000000000000000000000000000"
dvn_layerzero_labs = "0x0000000000000000000000000000000000000000"
dvn_google_cloud = "0x0000000000000000000000000000000000000000"
exp_minter_address = "0x0000000000000000000000000000000000000000"
supported_orchestrators = ["0xcb5CEf3C54aa90e9A7ad602A258D3d360cC862B9"]
orchestrator_deployed = "0xcb5CEf3C54aa90e9A7ad602A258D3d360cC862B9"
ithaca_account_deployed = "0x33aD2F49ab9f122f5F0FDF579f575724EfF353DE"
simulator_deployed = "0xb100Dc6e1BA9e54965fBB865F65Ac42b28BC25E8"
simple_funder_deployed = "0xBeD64199cAb1ccecFE6237e3202a832C09F9B961"
escrow_deployed = "0xf841803188076c7198852a9827059c30Fe4f0CAD"
simple_settler_deployed = "0xe5e477d959A78152FB87Cd77ba8793f7f5BAdfDc"
account_proxy_deployed = "0x4F4ddE38Da9F8AbBb96C48cA520b992D4bADc3D6"

[84532.uint]
chain_id = 84532
layerzero_eid = 0
target_balance = "1000000000000000"
default_num_signers = 2
layerzero_confirmations = 1
layerzero_max_message_size = 10000
layerzero_optional_dvn_threshold = 0
exp_mint_amount = "1000000000000000000000"
layerzero_destination_chain_ids = []

[84532.bytes32]
salt = "0xdf08a9fa957a9ac004f84f3a8ab7318a7be55d59948f46497bd3717865295b61"

[84532.string]
name = "Base Sepolia"
contracts = ["SimpleFunder"]
layerzero_required_dvns = ["dvn_layerzero_labs"]
layerzero_optional_dvns = []

[11155111]
endpoint_url = "${RPC_11155111}"

[11155111.bool]
is_testnet = true

[11155111.address]
funder_owner = "0x584b5274765a7f7c78fdc960248f38e5ad6b1edb"
funder_signer = "0x584b5274765a7f7c78fdc960248f38e5ad6b1edb"
settler_owner = "0x0000000000000000000000000000000000000000"
l0_settler_owner = "0x0000000000000000000000000000000000000000"
l0_settler_signer = "0x0000000000000000000000000000000000000000"
layerzero_endpoint = "0x0000000000000000000000000000000000000000"
layerzero_settler_address = "0x0000000000000000000000000000000000000000"
layerzero_send_uln302 = "0x0000000000000000000000000000000000000000"
layerzero_receive_uln302 = "0x0000000000000000000000000000000000000000"
dvn_layerzero_labs = "0x0000000000000000000000000000000000000000"
dvn_google_cloud = "0x0000000000000000000000000000000000000000"
exp_minter_address = "0x0000000000000000000000000000000000000000"
supported_orchestrators = ["0xcb5CEf3C54aa90e9A7ad602A258D3d360cC862B9"]
orchestrator_deployed = "0xcb5CEf3C54aa90e9A7ad602A258D3d360cC862B9"
ithaca_account_deployed = "0x33aD2F49ab9f122f5F0FDF579f575724EfF353DE"
simulator_deployed = "0xb100Dc6e1BA9e54965fBB865F65Ac42b28BC25E8"
simple_funder_deployed = "0x19E13F4cf8Efac2e6D5bec7a4052a37FfbbFc576"
account_proxy_deployed = "0x4F4ddE38Da9F8AbBb96C48cA520b992D4bADc3D6"

[11155111.uint]
chain_id = 11155111
layerzero_eid = 0
target_balance = "30000000000000000"
default_num_signers = 2
layerzero_confirmations = 1
layerzero_max_message_size = 10000
layerzero_optional_dvn_threshold = 0
exp_mint_amount = "1000000000000000000000"
layerzero_destination_chain_ids = []

[11155111.bytes32]
salt = "0xdf08a9fa957a9ac004f84f3a8ab7318a7be55d59948f46497bd3717865295b61"

[11155111.string]
name = "Eth Sepolia"
contracts = [
    "Orchestrator",
    "IthacaAccount",
    "Simulator",
    "SimpleFunder",
    "AccountProxy",
]
layerzero_required_dvns = ["dvn_layerzero_labs"]
layerzero_optional_dvns = []
